from pathlib import Path

# Fix setup classification expression generated by the production patch.
p=Path('unified-scanner/app/src/main/java/com/suhas/nseunifiedscanner/ScannerEngine.java')
s=p.read_text()
old='''        String setup=sweep.bullishSweep?"LIQUIDITY SWEEP RECLAIM":(sweep.realBreakout?"REAL BREAKOUT HOLD":(bullishHodBreakout?"BULLISH HOD BREAKOUT":(rsHard?"RELATIVE STRENGTH ACCEL":(PulseDiscoveryLogic.precursor(f.pulse1mPct,f.pulseAccel,f.dayPct)?"PULSE PRECURSOR":(f.crossedGreen&&recoveryHard?"EARLY RECOVERY":(f.microBreakoutPct>=-0.05&&f.microBreakoutPct<=0.25?"MICRO BREAKOUT":(volumeBuildHard?"VOLUME BUILD":"PRE-SPIKE"))))));\n'''
new='''        String setup;\n        if(sweep.bullishSweep)setup="LIQUIDITY SWEEP RECLAIM";\n        else if(sweep.realBreakout)setup="REAL BREAKOUT HOLD";\n        else if(bullishHodBreakout)setup="BULLISH HOD BREAKOUT";\n        else if(rsHard)setup="RELATIVE STRENGTH ACCEL";\n        else if(PulseDiscoveryLogic.precursor(f.pulse1mPct,f.pulseAccel,f.dayPct))setup="PULSE PRECURSOR";\n        else if(f.crossedGreen&&recoveryHard)setup="EARLY RECOVERY";\n        else if(f.microBreakoutPct>=-0.05&&f.microBreakoutPct<=0.25)setup="MICRO BREAKOUT";\n        else if(volumeBuildHard)setup="VOLUME BUILD";\n        else setup="PRE-SPIKE";\n'''
if old not in s: raise SystemExit('v3 compile-fix anchor missing')
p.write_text(s.replace(old,new,1))

# Learning backups use MediaStore.Downloads only behind an Android 10+ runtime gate.
# Annotate the helper itself so Android lint understands that contract; on API <29,
# backup()/restore() already return false before this helper can be reached.
b=Path('unified-scanner/app/src/main/java/com/suhas/nseunifiedscanner/LearningBackupManager.java')
t=b.read_text()
anchor='    private static String read(Context c)throws Exception{ContentResolver r=c.getContentResolver();Uri base=MediaStore.Downloads.EXTERNAL_CONTENT_URI;'
replacement='    @android.annotation.TargetApi(29)\n    private static String read(Context c)throws Exception{ContentResolver r=c.getContentResolver();Uri base=MediaStore.Downloads.EXTERNAL_CONTENT_URI;'
if anchor not in t: raise SystemExit('v3 backup lint-fix anchor missing')
b.write_text(t.replace(anchor,replacement,1))
print('v3 compile + lint fix applied')
