from pathlib import Path

ROOT=Path('unified-scanner/app/src/main/java/com/suhas/nseunifiedscanner')
TEST=Path('unified-scanner/app/src/test/java/com/suhas/nseunifiedscanner')

def rep(path,old,new):
    p=Path(path);s=p.read_text()
    if old not in s: raise SystemExit(f'v1.6.1 anchor missing in {p}: {old[:180]!r}')
    p.write_text(s.replace(old,new,1))

def opt(path,old,new):
    p=Path(path);s=p.read_text()
    if old in s:p.write_text(s.replace(old,new,1))

sp=ROOT/'ScannerEngine.java';tp=ROOT/'TradeSetupLogic.java';lp=ROOT/'LearningStore.java';lip=ROOT/'LearningInsights.java';mp=ROOT/'MainActivity.java';gp=Path('unified-scanner/app/build.gradle')

# Regime-aware HOD breakout. This is intentionally narrow: an old HOD may be crossed
# only before a vertical extension and only with strong early pressure, volume and depth.
rep(tp,
'''    static double clamp(double x,double lo,double hi){return Math.max(lo,Math.min(hi,x));}\n''',
'''    static boolean bullishHodBreakoutSetup(double breadth,double earlyPressure,double volumeAccel,double rsi1m,boolean macdAccel,boolean higherLows,double microBreakoutPct,double depthRatio,double spreadPct,double turnover,double hodRoomAfterTargetPct,boolean hodRejected,double price5mPct,boolean lateSpike) {\n        if(lateSpike || hodRejected) return false;\n        boolean normal = breadth>=55.0 && earlyPressure>=88.0 && volumeAccel>=1.50 && rsi1m>=50.0 && rsi1m<=65.0 &&\n                macdAccel && higherLows && microBreakoutPct>=-0.15 && microBreakoutPct<=0.30 && depthRatio>=0.55 &&\n                spreadPct<=0.18 && turnover>=60_000_000d && hodRoomAfterTargetPct>=-0.25 && price5mPct<=0.60;\n        boolean exceptionalVolume = breadth>=60.0 && earlyPressure>=88.0 && volumeAccel>=3.00 && rsi1m>=49.0 && rsi1m<=67.0 &&\n                macdAccel && microBreakoutPct>=-0.18 && microBreakoutPct<=0.35 && depthRatio>=0.50 && spreadPct<=0.20 &&\n                turnover>=60_000_000d && hodRoomAfterTargetPct>=-0.40 && price5mPct<=0.55;\n        return normal || exceptionalVolume;\n    }\n\n    static double clamp(double x,double lo,double hi){return Math.max(lo,Math.min(hi,x));}\n''')

rep(sp,
'''        boolean relativeStrengthHard=microReady && breadth<48.0 && f.dayPct>=0.25 && f.dayPct<=3.0 && f.oneHour>=-0.05 && depthRatio>=0.48 && turnover>=80_000_000d;\n        boolean clearPath=TradeSetupLogic.clearPath(entry,indicativeTarget,f.sessionHod,f.hodRejected,f.breakoutConfirmed,f.freshHodPressure);\n        boolean hard=(preSpikeHard||recoveryHard||volumeBuildHard||relativeStrengthHard)&&clearPath&&!f.lateSpike;\n''',
'''        boolean relativeStrengthHard=microReady && breadth<48.0 && f.dayPct>=0.25 && f.dayPct<=3.0 && f.oneHour>=-0.05 && depthRatio>=0.48 && turnover>=80_000_000d;\n        double hodRoom=TradeSetupLogic.roomBeyondTargetPct(indicativeTarget,f.sessionHod);\n        boolean classicClearPath=TradeSetupLogic.clearPath(entry,indicativeTarget,f.sessionHod,f.hodRejected,f.breakoutConfirmed,f.freshHodPressure);\n        boolean bullishHodBreakout=entry>=f.vwap && TradeSetupLogic.bullishHodBreakoutSetup(breadth,f.earlyPressure,f.volumeAccel,f.rsi1m,f.macd1mAccel,f.higherLows,f.microBreakoutPct,depthRatio,spreadPct,turnover,hodRoom,f.hodRejected,f.price5mPct,f.lateSpike);\n        boolean clearPath=classicClearPath||bullishHodBreakout;\n        boolean hard=(preSpikeHard||recoveryHard||volumeBuildHard||relativeStrengthHard||bullishHodBreakout)&&clearPath&&!f.lateSpike;\n''')

rep(sp,
'''            double hodRoom=TradeSetupLogic.roomBeyondTargetPct(indicativeTarget,f.sessionHod);features.put("hodroom",TradeSetupLogic.clamp((hodRoom+0.20)/1.20,0,1));features.put("recovery",TradeSetupLogic.clamp(f.recoveryPct/5.0,0,1));features.put("rejection",f.hodRejected&&!f.breakoutConfirmed?0:1);features.put("earlypress",TradeSetupLogic.clamp(f.earlyPressure/100.0,0,1));features.put("volaccel",TradeSetupLogic.clamp((f.volumeAccel-0.7)/2.0,0,1));features.put("compression",TradeSetupLogic.clamp(1.0-f.compressionPct/1.5,0,1));features.put("extension",f.lateSpike?0:TradeSetupLogic.clamp(1.0-Math.max(0,f.price5mPct)/1.4,0,1));features.put("lateSpike",f.lateSpike);features.put("preSpike",f.preSpike);features.put("price3mPct",f.price3mPct);features.put("price5mPct",f.price5mPct);features.put("volumeAccel",f.volumeAccel);features.put("compressionPct",f.compressionPct);features.put("earlyPressure",f.earlyPressure);\n            String setup=f.crossedGreen&&recoveryHard?"EARLY RECOVERY":(f.microBreakoutPct>=-0.05&&f.microBreakoutPct<=0.25?"MICRO BREAKOUT":(volumeBuildHard?"VOLUME BUILD":(relativeStrengthHard?"RELATIVE STRENGTH":"PRE-SPIKE")));features.put("setupType",setup);features.put("sessionHod",f.sessionHod);features.put("hodDistancePct",f.hodDistancePct);features.put("hodDrawdownPct",f.hodDrawdownPct);features.put("hodRoomAfterTargetPct",hodRoom);features.put("hodRejected",f.hodRejected);features.put("clearPath",clearPath);features.put("recoveryPct",f.recoveryPct);features.put("crossedGreen",f.crossedGreen);features.put("breakoutConfirmed",f.breakoutConfirmed);\n''',
'''            features.put("hodroom",TradeSetupLogic.clamp((hodRoom+0.20)/1.20,0,1));features.put("recovery",TradeSetupLogic.clamp(f.recoveryPct/5.0,0,1));features.put("rejection",f.hodRejected&&!f.breakoutConfirmed?0:1);features.put("earlypress",TradeSetupLogic.clamp(f.earlyPressure/100.0,0,1));features.put("volaccel",TradeSetupLogic.clamp((f.volumeAccel-0.7)/2.0,0,1));features.put("compression",TradeSetupLogic.clamp(1.0-f.compressionPct/1.5,0,1));features.put("extension",f.lateSpike?0:TradeSetupLogic.clamp(1.0-Math.max(0,f.price5mPct)/1.4,0,1));features.put("bullregime",TradeSetupLogic.clamp((breadth-45.0)/25.0,0,1));features.put("hodbreak",bullishHodBreakout?1:0);features.put("microsetup",f.microBreakoutPct>=-0.18&&f.microBreakoutPct<=0.35?1:0);features.put("lateSpike",f.lateSpike);features.put("preSpike",f.preSpike);features.put("price3mPct",f.price3mPct);features.put("price5mPct",f.price5mPct);features.put("volumeAccel",f.volumeAccel);features.put("compressionPct",f.compressionPct);features.put("earlyPressure",f.earlyPressure);features.put("breadthPct",breadth);\n            String setup=bullishHodBreakout?"BULLISH HOD BREAKOUT":(f.crossedGreen&&recoveryHard?"EARLY RECOVERY":(f.microBreakoutPct>=-0.05&&f.microBreakoutPct<=0.25?"MICRO BREAKOUT":(volumeBuildHard?"VOLUME BUILD":(relativeStrengthHard?"RELATIVE STRENGTH":"PRE-SPIKE"))));features.put("setupType",setup);features.put("sessionHod",f.sessionHod);features.put("hodDistancePct",f.hodDistancePct);features.put("hodDrawdownPct",f.hodDrawdownPct);features.put("hodRoomAfterTargetPct",hodRoom);features.put("hodRejected",f.hodRejected);features.put("classicClearPath",classicClearPath);features.put("bullishHodBreakout",bullishHodBreakout);features.put("clearPath",clearPath);features.put("recoveryPct",f.recoveryPct);features.put("crossedGreen",f.crossedGreen);features.put("breakoutConfirmed",f.breakoutConfirmed);\n''')

rep(sp,
'''        double score=f.baseScore + f.earlyPressure*0.22 + Math.min(7,liquidity*7) + Math.max(-4,Math.min(5,(depthRatio-0.5)*12)) - Math.max(0,(spreadPct-0.08)*20) + (recoveryHard?5:0) + (volumeBuildHard?5:0) + (relativeStrengthHard?4:0) + (f.higherLows?3:0) - (f.hodRejected&&!f.breakoutConfirmed?10:0) - (!clearPath?12:0) - (f.lateSpike?38:0);\n''',
'''        double score=f.baseScore + f.earlyPressure*0.22 + Math.min(7,liquidity*7) + Math.max(-4,Math.min(5,(depthRatio-0.5)*12)) - Math.max(0,(spreadPct-0.08)*20) + (recoveryHard?5:0) + (volumeBuildHard?5:0) + (relativeStrengthHard?4:0) + (bullishHodBreakout?7:0) + (f.higherLows?3:0) - (f.hodRejected&&!f.breakoutConfirmed?10:0) - (!clearPath?12:0) - (f.lateSpike?38:0);\n''')

rep(sp,
'''        if(r.qualified)return "QUALIFIED • "+setup+" • clear path to target + volume/VWAP/liquidity aligned";\n''',
'''        if(r.qualified&&r.features.optBoolean("bullishHodBreakout",false))return "QUALIFIED • BULLISH HOD BREAKOUT • early pressure + volume + bullish breadth confirmed through prior HOD";\n        if(r.qualified)return "QUALIFIED • "+setup+" • clear path to target + volume/VWAP/liquidity aligned";\n''')

# Add categorical/regime inputs to the actual adaptive model. Existing weights remain compatible.
rep(lp,
'''    static final String[] NAMES={"vwap","rsi","relvol","macd","momentum","breakout","liquidity","market","depth","range","time","hodroom","recovery","rejection","earlypress","volaccel","compression","extension"};\n    private static final double[] DEFAULT={0.92,0.55,0.78,0.72,0.62,0.58,0.68,0.55,0.35,0.35,0.45,0.62,0.52,0.68,0.82,0.72,0.58,0.74};\n''',
'''    static final String[] NAMES={"vwap","rsi","relvol","macd","momentum","breakout","liquidity","market","depth","range","time","hodroom","recovery","rejection","earlypress","volaccel","compression","extension","bullregime","hodbreak","microsetup"};\n    private static final double[] DEFAULT={0.92,0.55,0.78,0.72,0.62,0.58,0.68,0.55,0.35,0.35,0.45,0.62,0.52,0.68,0.82,0.72,0.58,0.74,0.38,0.30,0.28};\n''')

# Segmented diagnostics show which subsets are actually hitting instead of one aggregate shadow rate.
rep(lip,'import android.database.sqlite.SQLiteDatabase;\n','import android.database.sqlite.SQLiteDatabase;\n\nimport org.json.JSONObject;\n')
rep(lip,
'''    synchronized PipelineStats pipelineStats(){\n''',
'''    synchronized SegmentedStats segmentedStats(){\n        SegmentedStats s=new SegmentedStats();long[] b=todayBounds();\n        try(SQLiteDatabase db=open();Cursor c=db.rawQuery("SELECT status,features FROM shadow_samples WHERE resolved_ms>=? AND resolved_ms<? AND status IN ('SUCCESS','FAIL','TIMEOUT')",new String[]{String.valueOf(b[0]),String.valueOf(b[1])})){\n            while(c.moveToNext()){String status=c.getString(0),raw=c.getString(1);boolean hit="SUCCESS".equals(status);try{JSONObject f=new JSONObject(raw);double ep=f.optDouble("earlyPressure",0),breadth=f.optDouble("breadthPct",-1);String setup=f.optString("setupType","");boolean hod=f.optBoolean("bullishHodBreakout",false)||"BULLISH HOD BREAKOUT".equals(setup);if(ep>=90){s.early90N++;if(hit)s.early90Hits++;}if(breadth>=55){s.bullN++;if(hit)s.bullHits++;}if(hod){s.hodBreakN++;if(hit)s.hodBreakHits++;}if("MICRO BREAKOUT".equals(setup)||"BULLISH HOD BREAKOUT".equals(setup)){s.microN++;if(hit)s.microHits++;}}catch(Exception ignore){}}\n        }catch(Exception ignore){}\n        return s;\n    }\n\n    synchronized PipelineStats pipelineStats(){\n''')
rep(lip,
'''    static final class PipelineStats{int observed,shadowObserved,qualified,pending,hits,stops,timeouts;}\n''',
'''    static final class PipelineStats{int observed,shadowObserved,qualified,pending,hits,stops,timeouts;}\n    static final class SegmentedStats{int early90N,early90Hits,bullN,bullHits,hodBreakN,hodBreakHits,microN,microHits;}\n''')

rep(mp,
'''        renderHistory();renderConnectivity();LearningInsights.ShadowStats sh=insights.shadowStats();learningMeta.setText("Shadow learning today: "+sh.resolvedToday+" resolved • "+sh.hitsToday+" target-first • "+sh.pending+" pending. Shadow outcomes train at adaptive 8–20% weight and never alter the headline accuracy score.");\n''',
'''        renderHistory();renderConnectivity();LearningInsights.ShadowStats sh=insights.shadowStats();LearningInsights.SegmentedStats seg=insights.segmentedStats();learningMeta.setText("Shadow learning today: "+sh.resolvedToday+" resolved • "+sh.hitsToday+" target-first • "+sh.pending+" pending. Shadow outcomes train at adaptive 8–20% weight and never alter the headline accuracy score.\\nSegments: EARLY≥90 "+seg.early90Hits+"/"+seg.early90N+" • bullish breadth "+seg.bullHits+"/"+seg.bullN+" • micro/HOD breakout "+seg.microHits+"/"+seg.microN+" • HOD override "+seg.hodBreakHits+"/"+seg.hodBreakN);\n''')

rep(mp,
'''        b.append(r.features.optBoolean("clearPath",true)?"✓PATH ":"✗PATH ");\n        b.append(r.features.optBoolean("hodRejected",false)?"✗HOD-REJECT ":"✓HOD ");\n''',
'''        b.append(r.features.optBoolean("clearPath",true)?"✓PATH ":"✗PATH ");\n        if(r.features.optBoolean("bullishHodBreakout",false))b.append("✓HOD-BREAK ");else b.append(r.features.optBoolean("hodRejected",false)?"✗HOD-REJECT ":"✓HOD ");\n''')

opt(mp,
'''BUY-qualified calls keep the official +0.30% net accuracy score. Ranks 4–15 are forward shadow snapshots. v1.6 learns pre-spike pressure, 1-minute volume acceleration, compression, higher lows, VWAP location, recovery and HOD resistance. Late vertical spikes are penalized.''',
'''BUY-qualified calls keep the official +0.30% net accuracy score. Ranks 4–15 are forward shadow snapshots. v1.6.1 additionally learns bullish-regime and HOD-breakout subsets instead of treating every shadow sample alike. Late vertical spikes are still penalized.''')
opt(mp,'v1.6.0 • standalone package com.suhas.nseunifiedscanner','v1.6.1 • standalone package com.suhas.nseunifiedscanner')

rep(gp,"versionCode 160\n        versionName '1.6.0'","versionCode 161\n        versionName '1.6.1'")

(TEST/'BullishHodBreakoutTest.java').write_text('''package com.suhas.nseunifiedscanner;\nimport org.junit.Test;\nimport static org.junit.Assert.*;\npublic class BullishHodBreakoutTest {\n @Test public void strongBullishPressureCanCrossSmallHodGap(){assertTrue(TradeSetupLogic.bullishHodBreakoutSetup(68,92,1.8,57,true,true,0.08,0.61,0.12,120_000_000,-0.20,false,0.24,false));}\n @Test public void lowVolumeCannotOverrideHod(){assertFalse(TradeSetupLogic.bullishHodBreakoutSetup(70,94,0.7,56,true,true,0.05,0.62,0.10,150_000_000,-0.12,false,0.18,false));}\n @Test public void priorHodRejectionCannotUseOverride(){assertFalse(TradeSetupLogic.bullishHodBreakoutSetup(72,95,4.2,58,true,true,0.06,0.64,0.10,200_000_000,-0.18,true,0.20,false));}\n @Test public void lateSpikeCannotUseOverride(){assertFalse(TradeSetupLogic.bullishHodBreakoutSetup(72,96,4.0,58,true,true,0.08,0.65,0.10,220_000_000,-0.18,false,1.20,true));}\n @Test public void exceptionalVolumeAllowsSlightlyDeeperCross(){assertTrue(TradeSetupLogic.bullishHodBreakoutSetup(72,91,5.5,59,true,false,0.12,0.54,0.16,180_000_000,-0.36,false,0.15,false));}\n}\n''')

print('v1.6.1 bullish HOD breakout + segmented learning patch applied')
