from pathlib import Path

ROOT=Path('unified-scanner/app/src/main/java/com/suhas/nseunifiedscanner')
TEST=Path('unified-scanner/app/src/test/java/com/suhas/nseunifiedscanner')

def rep(path,old,new):
    p=Path(path);s=p.read_text()
    if old not in s: raise SystemExit(f'v1.6 anchor missing in {p}: {old[:180]!r}')
    p.write_text(s.replace(old,new,1))

def opt(path,old,new):
    p=Path(path);s=p.read_text()
    if old in s:p.write_text(s.replace(old,new,1))

sp=ROOT/'ScannerEngine.java'; lp=ROOT/'LearningStore.java'; lip=ROOT/'LearningInsights.java'; mp=ROOT/'MainActivity.java'; up=ROOT/'UnifiedService.java'; gp=Path('unified-scanner/app/build.gradle')

logic='''package com.suhas.nseunifiedscanner;\n\n/** Pure deterministic pre-spike pressure classifier used by ScannerEngine and unit tests. */\nfinal class PreSpikeLogic {\n    private PreSpikeLogic(){}\n    static Assessment assess(double price3,double price5,double extension10,double lastRange,double dayPct,double vwapDist,double volAccel,double rsi,boolean macdAccel,boolean higherLows,double compression,double microBreakout){\n        boolean late = price3>=1.05 || price5>=1.45 || extension10>=1.90 || lastRange>=1.10 || dayPct>=4.0 || vwapDist>=1.90;\n        double p=28.0;\n        p+=Math.min(22.0,Math.max(0.0,(volAccel-0.90)*18.0));\n        p+=Math.max(0.0,14.0-Math.abs(rsi-56.0)*1.10);\n        p+=macdAccel?11.0:0.0;\n        p+=higherLows?9.0:0.0;\n        p+=compression>=0.12&&compression<=0.95?10.0:compression<=1.25?5.0:0.0;\n        p+=vwapDist>=-0.20&&vwapDist<=0.80?9.0:vwapDist<=1.15?4.0:0.0;\n        p+=microBreakout>=-0.18&&microBreakout<=0.28?8.0:0.0;\n        if(price5>0.90)p-=12.0;if(price3>0.65)p-=8.0;if(dayPct>3.0)p-=10.0;if(late)p-=42.0;\n        p=Math.max(0.0,Math.min(99.0,p));\n        boolean quietPrice=price5>=-0.45&&price5<=0.90&&price3<=0.70;\n        boolean pre=!late && p>=66.0 && volAccel>=1.12 && rsi>=47.0&&rsi<=68.0 && quietPrice && vwapDist>=-0.25&&vwapDist<=1.15 && (macdAccel||higherLows);\n        return new Assessment(p,pre,late);\n    }\n    static final class Assessment{final double pressure;final boolean preSpike,lateSpike;Assessment(double p,boolean pre,boolean late){pressure=p;preSpike=pre;lateSpike=late;}}\n}\n'''
(ROOT/'PreSpikeLogic.java').write_text(logic)

test='''package com.suhas.nseunifiedscanner;\nimport org.junit.Test;\nimport static org.junit.Assert.*;\npublic class PreSpikeLogicTest {\n @Test public void quietVolumeBuildQualifiesEarly(){PreSpikeLogic.Assessment a=PreSpikeLogic.assess(0.18,0.34,0.55,0.32,0.65,0.28,1.85,55,true,true,0.48,-0.05);assertTrue(a.preSpike);assertFalse(a.lateSpike);assertTrue(a.pressure>=66);}\n @Test public void verticalFiveMinuteSpikeIsLate(){PreSpikeLogic.Assessment a=PreSpikeLogic.assess(1.25,1.90,2.20,1.30,5.20,2.10,3.0,71,true,true,1.8,0.7);assertTrue(a.lateSpike);assertFalse(a.preSpike);}\n @Test public void weakVolumeDoesNotQualify(){PreSpikeLogic.Assessment a=PreSpikeLogic.assess(0.10,0.20,0.30,0.25,0.30,0.10,0.88,54,true,true,0.40,-0.10);assertFalse(a.preSpike);}\n @Test public void alreadyExtendedFromVwapIsLate(){PreSpikeLogic.Assessment a=PreSpikeLogic.assess(0.30,0.60,1.30,0.40,2.40,2.05,1.9,60,true,true,0.50,0.05);assertTrue(a.lateSpike);assertFalse(a.preSpike);}\n}\n'''
(TEST/'PreSpikeLogicTest.java').write_text(test)

rep(sp,
'''if(l<20||l>10000||day<-0.60||day>9.0)continue;\n                double fromOpen=(l/o.open-1.0)*100.0; double nearHigh=o.high>0?(o.high-l)/l*100.0:9;\n                double recoveryPct=o.low>0?(l/o.low-1.0)*100.0:0; boolean crossedGreen=o.low<o.close*0.998&&l>o.close*1.0005;\n                if(fromOpen<-0.60||nearHigh>4.00)continue;\n                PreCandidate p=new PreCandidate();p.instrument=ins;p.ltp=l;p.ohlc=o;p.dayPct=day;p.fromOpenPct=fromOpen;p.recoveryPct=recoveryPct;p.crossedGreen=crossedGreen;\n                p.preScore=day*3.5+Math.max(0,3.00-nearHigh)*2.2+Math.max(0,fromOpen)*1.4+(crossedGreen?8.0:0)+Math.min(6.0,Math.max(0,recoveryPct-1.0)*1.4);''',
'''if(l<20||l>10000||day<-3.0||day>4.5)continue;\n                double fromOpen=(l/o.open-1.0)*100.0; double nearHigh=o.high>0?(o.high-l)/l*100.0:9;\n                double recoveryPct=o.low>0?(l/o.low-1.0)*100.0:0; boolean crossedGreen=o.low<o.close*0.998&&l>o.close*1.0005;\n                if(fromOpen<-2.50||fromOpen>3.50||nearHigh>5.50)continue;\n                PreCandidate p=new PreCandidate();p.instrument=ins;p.ltp=l;p.ohlc=o;p.dayPct=day;p.fromOpenPct=fromOpen;p.recoveryPct=recoveryPct;p.crossedGreen=crossedGreen;\n                double daySweet=Math.max(0,12.0-Math.abs(day-0.45)*3.0);double hodApproach=Math.max(0,7.0-Math.abs(nearHigh-0.75)*3.0);double recoverySweet=(crossedGreen?5.0:0)+Math.min(5.0,Math.max(0,recoveryPct-0.8));\n                p.preScore=daySweet+hodApproach+recoverySweet+Math.max(0,4.0-Math.abs(fromOpen-0.35)*1.8)-(day>3.0?12.0:0)-(fromOpen>2.5?9.0:0);''')

rep(sp,
'''f.baseScore=35 + Math.min(14,Math.max(0,oneHour*5)) + Math.min(12,Math.max(0,(relVol-1)*8)) + (entry>vwap?9:0) + (macd.hist>0&&macd.hist>macd.prevHist?10:4) + Math.max(0,8-Math.abs(rsi-62)*0.7) + Math.max(0,8-Math.abs(distR1)*8) + Math.min(8,Math.max(0,roomR2*5)) + (path.crossedGreen?6:0) + (path.freshHodPressure?4:0) - (path.hodRejected?8:0);''',
'''double modestMomentum=Math.max(0,11.0-Math.abs(oneHour-0.55)*7.0);double extensionPenalty=Math.max(0,oneHour-1.35)*11.0+Math.max(0,p.dayPct-3.0)*9.0;\n        f.baseScore=30 + modestMomentum + Math.min(14,Math.max(0,(relVol-0.85)*9)) + (entry>vwap?7:2) + (macd.hist>=macd.prevHist?9:1) + Math.max(0,10-Math.abs(rsi-56)*0.75) + Math.max(0,6-Math.abs(distR1)*5) + Math.min(6,Math.max(0,roomR2*4)) + (path.crossedGreen?5:0) + (path.freshHodPressure?3:0) - (path.hodRejected?8:0) - extensionPenalty;''')

rep(sp,
'''            for(FeatureCandidate fc:technical){\n                GrowwApi.Result<GrowwApi.Quote> qr=GrowwApi.quote(token,fc.instrument.symbol);''',
'''            LocalDateTime microEnd=LocalDateTime.now(IST).minusMinutes(1).withSecond(59).withNano(0);LocalDateTime microStart=microEnd.minusMinutes(95);\n            for(FeatureCandidate fc:technical){\n                GrowwApi.Result<List<GrowwApi.Candle>> micro=GrowwApi.candles(token,fc.instrument.growwSymbol,microStart.format(API_TIME),microEnd.format(API_TIME),"1minute");if(micro.ok)applyPreSpike(fc,micro.value);\n                GrowwApi.Result<GrowwApi.Quote> qr=GrowwApi.quote(token,fc.instrument.symbol);''')

method='''\n    private void applyPreSpike(FeatureCandidate f,List<GrowwApi.Candle> c){\n        int n=c==null?0:c.size();if(n<24)return;double[] close=new double[n],high=new double[n],low=new double[n],vol=new double[n];for(int i=0;i<n;i++){GrowwApi.Candle x=c.get(i);close[i]=x.close;high[i]=x.high;low[i]=x.low;vol[i]=x.volume;}\n        double price3=(close[n-1]/close[Math.max(0,n-4)]-1.0)*100.0;double price5=(close[n-1]/close[Math.max(0,n-6)]-1.0)*100.0;double extension10=(close[n-1]/close[Math.max(0,n-11)]-1.0)*100.0;\n        double recent=0;for(int i=n-3;i<n;i++)recent+=vol[i];recent/=3.0;double base=0;int bc=0;for(int i=Math.max(0,n-15);i<n-3;i++){base+=vol[i];bc++;}base=bc>0?base/bc:0;double volAccel=base>0?recent/base:0;\n        double ch=-Double.MAX_VALUE,cl=Double.MAX_VALUE;for(int i=Math.max(0,n-13);i<n-2;i++){ch=Math.max(ch,high[i]);cl=Math.min(cl,low[i]);}double compression=(ch>0&&cl<Double.MAX_VALUE)?(ch/cl-1.0)*100.0:9;\n        double lastRange=(high[n-1]/Math.max(0.01,low[n-1])-1.0)*100.0;double vwapDist=(f.entry/f.vwap-1.0)*100.0;double microHigh=0;for(int i=Math.max(0,n-18);i<n-2;i++)microHigh=Math.max(microHigh,high[i]);double microBreakout=microHigh>0?(close[n-1]/microHigh-1.0)*100.0:0;\n        double rsi1=Indicators.rsi(close,14);Indicators.Macd m1=Indicators.macd(close);boolean macdAccel=m1.hist>=m1.prevHist;boolean higherLows=low[n-1]>=low[n-3]&&low[n-3]>=low[n-5];\n        PreSpikeLogic.Assessment a=PreSpikeLogic.assess(price3,price5,extension10,lastRange,f.dayPct,vwapDist,volAccel,rsi1,macdAccel,higherLows,compression,microBreakout);\n        f.earlyPressure=a.pressure;f.preSpike=a.preSpike;f.lateSpike=a.lateSpike;f.price3mPct=price3;f.price5mPct=price5;f.extension10mPct=extension10;f.volumeAccel=volAccel;f.compressionPct=compression;f.microBreakoutPct=microBreakout;f.rsi1m=rsi1;f.macd1mAccel=macdAccel;f.higherLows=higherLows;\n    }\n\n'''
rep(sp,'\n    private Recommendation score(FeatureCandidate f,double breadth,int minScore,int modelN){',method+'    private Recommendation score(FeatureCandidate f,double breadth,int minScore,int modelN){')

old='''double indicativeTarget=GrowwApi.roundToTick(entry*1.0070,f.instrument.tick,true);\n        // v1.5: weak breadth must not automatically kill strong individual leaders.\n        double relFloor=breadth>=58.0?1.10:(breadth<40.0?1.18:1.15);\n        double momFloor=breadth>=58.0?0.20:(breadth<40.0?0.25:0.28);\n        double spreadFloor=0.20;\n        boolean structuralRoom=roomR2>=0.35||f.breakoutConfirmed||f.freshHodPressure;\n        boolean momentumHard=entry>f.vwap && f.rsi>=52 && f.rsi<=74 && f.relVol>=relFloor && f.macd.hist>0 && f.macd.hist>=f.macd.prevHist && f.oneHour>=momFloor && f.oneHour<=4.5 && spreadPct<=spreadFloor && turnover>=75_000_000d && structuralRoom && circuitRoom>=0.80;\n        boolean recoveryClassic=entry>f.vwap && TradeSetupLogic.recoverySetup(f.crossedGreen,f.recoveryPct,f.fromOpenPct,f.rsi,f.relVol,f.macd.hist,f.macd.prevHist,f.oneHour,spreadPct,turnover,roomR2,circuitRoom,breadth,depthRatio);\n        boolean recoveryFast=entry>=f.vwap*0.999 && f.crossedGreen && f.recoveryPct>=1.10 && f.recoveryPct<=9.0 && f.fromOpenPct>=0.15 && f.rsi>=50 && f.rsi<=72 && f.relVol>=1.05 && (f.macd.hist>0||f.macd.hist>=f.macd.prevHist) && f.oneHour>=0.05 && spreadPct<=0.20 && turnover>=75_000_000d && structuralRoom && circuitRoom>=0.80 && (breadth>=30.0||depthRatio>=0.56);\n        boolean recoveryHard=recoveryClassic||recoveryFast;\n        boolean volumeIgnitionHard=entry>=f.vwap*0.999 && TradeSetupLogic.volumeIgnitionSetup(f.rsi,f.relVol,f.macd.hist,f.macd.prevHist,f.oneHour,spreadPct,turnover,Math.max(roomR2,0.68),circuitRoom,breadth,depthRatio,f.wickRatio);\n        boolean relativeStrengthHard=breadth<48.0 && f.dayPct>=0.75 && entry>=f.vwap*1.0005 && f.rsi>=52 && f.rsi<=74 && f.relVol>=1.05 && (f.macd.hist>0||f.macd.hist>=f.macd.prevHist) && f.oneHour>=0.12 && spreadPct<=0.20 && turnover>=100_000_000d && structuralRoom && circuitRoom>=0.80 && depthRatio>=0.48;\n        boolean vwapTrendHard=entry>=f.vwap*1.0010 && f.rsi>=52 && f.rsi<=72 && f.relVol>=1.10 && f.macd.hist>=f.macd.prevHist && f.oneHour>=0.18 && spreadPct<=0.18 && turnover>=100_000_000d && structuralRoom && circuitRoom>=0.80 && depthRatio>=0.50;\n        boolean clearPath=TradeSetupLogic.clearPath(entry,indicativeTarget,f.sessionHod,f.hodRejected,f.breakoutConfirmed,f.freshHodPressure);\n        boolean hard=(momentumHard||recoveryHard||volumeIgnitionHard||relativeStrengthHard||vwapTrendHard)&&clearPath;\n        double liquidity=Math.min(1.0,turnover/300_000_000d); double market=AdaptiveModel.clamp((breadth-40)/35.0,0,1);'''
new='''double indicativeTarget=GrowwApi.roundToTick(entry*1.0048,f.instrument.tick,true);\n        double spreadFloor=0.20;boolean structuralRoom=roomR2>=0.22||f.breakoutConfirmed||f.freshHodPressure;\n        boolean microReady=f.preSpike&&f.earlyPressure>=66.0&&!f.lateSpike;\n        boolean preSpikeHard=microReady && entry>=f.vwap*0.9975 && f.rsi>=48 && f.rsi<=70 && f.relVol>=0.90 && f.volumeAccel>=1.12 && spreadPct<=spreadFloor && turnover>=60_000_000d && structuralRoom && circuitRoom>=0.65 && depthRatio>=0.44;\n        boolean recoveryHard=microReady && f.crossedGreen && f.recoveryPct>=0.80 && f.fromOpenPct>=-0.10 && spreadPct<=0.20 && turnover>=60_000_000d && (breadth>=28.0||depthRatio>=0.52);\n        boolean volumeBuildHard=microReady && f.volumeAccel>=1.45 && f.rsi1m>=49&&f.rsi1m<=67 && f.macd1mAccel && spreadPct<=0.20 && turnover>=60_000_000d;\n        boolean relativeStrengthHard=microReady && breadth<48.0 && f.dayPct>=0.25 && f.dayPct<=3.0 && f.oneHour>=-0.05 && depthRatio>=0.48 && turnover>=80_000_000d;\n        boolean clearPath=TradeSetupLogic.clearPath(entry,indicativeTarget,f.sessionHod,f.hodRejected,f.breakoutConfirmed,f.freshHodPressure);\n        boolean hard=(preSpikeHard||recoveryHard||volumeBuildHard||relativeStrengthHard)&&clearPath&&!f.lateSpike;\n        double liquidity=Math.min(1.0,turnover/300_000_000d); double market=AdaptiveModel.clamp((breadth-40)/35.0,0,1);'''
rep(sp,old,new)

rep(sp,
'''features.put("setupType",recoveryHard?"RECOVERY":(volumeIgnitionHard?"VOLUME IGNITION":(relativeStrengthHard?"RELATIVE STRENGTH":(vwapTrendHard?"VWAP TREND":(f.breakoutConfirmed||f.freshHodPressure?"HOD MOMENTUM":"MOMENTUM")))));''',
'''String setup=f.crossedGreen&&recoveryHard?"EARLY RECOVERY":(f.microBreakoutPct>=-0.05&&f.microBreakoutPct<=0.25?"MICRO BREAKOUT":(volumeBuildHard?"VOLUME BUILD":(relativeStrengthHard?"RELATIVE STRENGTH":"PRE-SPIKE")));features.put("setupType",setup);''')

rep(sp,
'''double hodRoom=TradeSetupLogic.roomBeyondTargetPct(indicativeTarget,f.sessionHod);features.put("hodroom",TradeSetupLogic.clamp((hodRoom+0.20)/1.20,0,1));features.put("recovery",TradeSetupLogic.clamp(f.recoveryPct/5.0,0,1));features.put("rejection",f.hodRejected&&!f.breakoutConfirmed?0:1);''',
'''double hodRoom=TradeSetupLogic.roomBeyondTargetPct(indicativeTarget,f.sessionHod);features.put("hodroom",TradeSetupLogic.clamp((hodRoom+0.20)/1.20,0,1));features.put("recovery",TradeSetupLogic.clamp(f.recoveryPct/5.0,0,1));features.put("rejection",f.hodRejected&&!f.breakoutConfirmed?0:1);features.put("earlypress",TradeSetupLogic.clamp(f.earlyPressure/100.0,0,1));features.put("volaccel",TradeSetupLogic.clamp((f.volumeAccel-0.7)/2.0,0,1));features.put("compression",TradeSetupLogic.clamp(1.0-f.compressionPct/1.5,0,1));features.put("extension",f.lateSpike?0:TradeSetupLogic.clamp(1.0-Math.max(0,f.price5mPct)/1.4,0,1));features.put("lateSpike",f.lateSpike);features.put("preSpike",f.preSpike);features.put("price3mPct",f.price3mPct);features.put("price5mPct",f.price5mPct);features.put("volumeAccel",f.volumeAccel);features.put("compressionPct",f.compressionPct);features.put("earlyPressure",f.earlyPressure);''')

rep(sp,
'''double score=f.baseScore + Math.min(8,liquidity*8) + Math.max(-4,Math.min(5,(depthRatio-0.5)*12)) - Math.max(0,(spreadPct-0.08)*20) - Math.max(0,(f.rsi-70)*1.4) - Math.max(0,(f.wickRatio-0.9)*2.5) + (recoveryHard?6:0) + (volumeIgnitionHard?5:0) + (relativeStrengthHard?6:0) + (vwapTrendHard?4:0) + (f.breakoutConfirmed?4:0) - (f.hodRejected&&!f.breakoutConfirmed?10:0) - (!clearPath?12:0);''',
'''double score=f.baseScore + f.earlyPressure*0.22 + Math.min(7,liquidity*7) + Math.max(-4,Math.min(5,(depthRatio-0.5)*12)) - Math.max(0,(spreadPct-0.08)*20) + (recoveryHard?5:0) + (volumeBuildHard?5:0) + (relativeStrengthHard?4:0) + (f.higherLows?3:0) - (f.hodRejected&&!f.breakoutConfirmed?10:0) - (!clearPath?12:0) - (f.lateSpike?38:0);''')

rep(sp,
'''int effectiveMin=modelN<30?Math.min(minScore,78):minScore;double modelGate=modelN<30?0.0:(modelN<60?0.62:0.72);boolean qualified=hard && score>=effectiveMin && (modelN<30||probability>=modelGate);''',
'''int effectiveMin=modelN<30?Math.min(minScore,74):(modelN<60?Math.min(minScore,78):minScore);double modelGate=modelN<30?0.0:(modelN<60?0.58:0.68);boolean qualified=hard && score>=effectiveMin && (modelN<30||probability>=modelGate);''')

rep(sp,
'''double rr=(target-entry)/Math.max(0.01,entry-stop); if(rr<1.35)hard=false;''',
'''double rr=(target-entry)/Math.max(0.01,entry-stop); if(rr<1.20)hard=false;''')

rep(sp,',"5minute"); if(!hr.ok)continue;\n                String outcome=null; for(GrowwApi.Candle c:hr.value){boolean hitT=c.high>=r.target;boolean hitS=c.low<=r.stop;',',"1minute"); if(!hr.ok)continue;\n                String outcome=null; for(GrowwApi.Candle c:hr.value){boolean hitT=c.high>=r.target;boolean hitS=c.low<=r.stop;')
rep(sp,',"5minute");if(!hr.ok)continue;\n                String outcome=null;for(GrowwApi.Candle c:hr.value){boolean t=c.high>=r.target,s=c.low<=r.stop;',',"1minute");if(!hr.ok)continue;\n                String outcome=null;for(GrowwApi.Candle c:hr.value){boolean t=c.high>=r.target,s=c.low<=r.stop;')

rep(sp,
'''for(int i=0;i<Math.min(10,recs.size());i++){Recommendation x=recs.get(i);if(i>=3||!x.qualified)insights.recordShadowIfNew(x);}''',
'''for(int i=0;i<Math.min(15,recs.size());i++){Recommendation x=recs.get(i);if(i>=3||!x.qualified)insights.recordShadowIfNew(x);}''')

rep(sp,
'''double entry,rsi,relVol,atr,oneHour,vwap,r1,r2,distR1,roomR2,wickRatio,dayPct,baseScore,sessionHod,hodDistancePct,hodDrawdownPct,recoveryPct,fromOpenPct;boolean crossedGreen,breakoutConfirmed,freshHodPressure,hodRejected;''',
'''double entry,rsi,relVol,atr,oneHour,vwap,r1,r2,distR1,roomR2,wickRatio,dayPct,baseScore,sessionHod,hodDistancePct,hodDrawdownPct,recoveryPct,fromOpenPct,earlyPressure,price3mPct,price5mPct,extension10mPct,volumeAccel,compressionPct,microBreakoutPct,rsi1m;boolean crossedGreen,breakoutConfirmed,freshHodPressure,hodRejected,preSpike,lateSpike,macd1mAccel,higherLows;''')

rep(lp,
'''static final String[] NAMES={"vwap","rsi","relvol","macd","momentum","breakout","liquidity","market","depth","range","time","hodroom","recovery","rejection"};\n    private static final double[] DEFAULT={0.92,0.55,0.78,0.72,0.62,0.58,0.68,0.55,0.35,0.35,0.45,0.62,0.52,0.68};''',
'''static final String[] NAMES={"vwap","rsi","relvol","macd","momentum","breakout","liquidity","market","depth","range","time","hodroom","recovery","rejection","earlypress","volaccel","compression","extension"};\n    private static final double[] DEFAULT={0.92,0.55,0.78,0.72,0.62,0.58,0.68,0.55,0.35,0.35,0.45,0.62,0.52,0.68,0.82,0.72,0.58,0.74};''')
opt(lp,'else if(s.rate>=86.0 && s.n>=50) minScore=Math.max(80,minScore-1);','else if(s.rate>=86.0 && s.n>=50) minScore=Math.max(76,minScore-1);')

rep(lip,
'''if(System.currentTimeMillis()-last<10*60_000L && Math.abs(r.entry-old)/Math.max(0.01,old)<0.003)return -1;''',
'''if(System.currentTimeMillis()-last<5*60_000L && Math.abs(r.entry-old)/Math.max(0.01,old)<0.002)return -1;''')

rep(up,
'''double target=ChargeModel.requiredSellPrice(fillPrice,filled,0.005,0.0007,rec.tick);''',
'''double target=ChargeModel.requiredSellPrice(fillPrice,filled,0.003,0.0006,rec.tick);''')

opt(mp,'5-minute adaptive intraday engine • HOD-aware • 30-minute horizon','1-minute pre-spike pressure • 5-minute confirmation • 30-minute horizon')
opt(mp,'ACCURACY SCORE • 30-MIN','0.30% NET ACCURACY • 30-MIN')
opt(mp,'TOP 3 • NEXT 30 MINUTES','EARLY RADAR • NEXT 30 MINUTES')
opt(mp,'A ranked Top 3 is shown whenever the discovery scan has enough data. BUY appears only when strict hard gates + learned quality threshold pass. Same stock may remain ranked on consecutive scans.','Ranks developing pressure BEFORE a vertical move using 1-minute volume acceleration, compression, VWAP location, higher lows and micro-breakout pressure. Completed spikes are penalized. BUY still requires hard execution/path gates.')
opt(mp,'NET OBJECTIVE +0.50% after estimated Groww/NSE charges • actual target recalculated from fill + quantity','NET OBJECTIVE +0.30% after estimated Groww/NSE charges • actual target recalculated from fill + quantity')
opt(mp,'+0.50% net objective','+0.30% net objective')
opt(mp,'+0.50% executable-net profit lock','+0.30% primary target')
opt(mp,
'''c.addView(txt("Setup "+setup+" • prior HOD "+(hod>0?("₹"+money(hod)):"—")+" • target-clearance "+String.format(Locale.US,"%+.2f%%",hodRoom)+" • recovery "+String.format(Locale.US,"%.2f%%",recov),11,r.features.optBoolean("clearPath",true)?MUTED:RED,false));c.addView(space(8));''',
'''double ep=r.features.optDouble("earlyPressure",0),va=r.features.optDouble("volumeAccel",0),p5=r.features.optDouble("price5mPct",0);boolean late=r.features.optBoolean("lateSpike",false);c.addView(txt("Setup "+setup+" • EARLY "+String.format(Locale.US,"%.0f/100",ep)+" • vol accel "+String.format(Locale.US,"%.2fx",va)+" • 5m "+String.format(Locale.US,"%+.2f%%",p5)+(late?" • LATE SPIKE ✗":""),11,late?RED:ACCENT,false));c.addView(txt("prior HOD "+(hod>0?("₹"+money(hod)):"—")+" • target-clearance "+String.format(Locale.US,"%+.2f%%",hodRoom)+" • recovery "+String.format(Locale.US,"%.2f%%",recov),11,r.features.optBoolean("clearPath",true)?MUTED:RED,false));c.addView(space(8));''')
opt(mp,'v1.5.0 • standalone package com.suhas.nseunifiedscanner','v1.6.0 • standalone package com.suhas.nseunifiedscanner')

rep(gp,"versionCode 150\n        versionName '1.5.0'","versionCode 160\n        versionName '1.6.0'")

print('v1.6 pre-spike + 0.30 net target patch applied')
