from pathlib import Path

ROOT=Path('unified-scanner/app/src/main/java/com/suhas/nseunifiedscanner')

def must_replace(path, old, new, count=1):
    p=Path(path)
    s=p.read_text()
    found=s.count(old)
    if found < count:
        raise SystemExit(f'Patch anchor missing in {p}: expected >= {count}, found {found}: {old[:120]!r}')
    s=s.replace(old,new,count)
    p.write_text(s)

# ---------------- ScannerEngine: wider discovery + HOD clear-path + recovery setup ----------------
sp=ROOT/'ScannerEngine.java'
must_replace(sp,'private static final int TOP_PREFILTER=32;\n    private static final int TOP_QUOTE=18;','private static final int TOP_PREFILTER=40;\n    private static final int TOP_QUOTE=22;')

must_replace(sp,
'''if(l<20||l>10000||day<-0.15||day>9.0)continue;\n                double fromOpen=(l/o.open-1.0)*100.0; double nearHigh=o.high>0?(o.high-l)/l*100.0:9;\n                if(fromOpen<-0.35||nearHigh>3.00)continue;\n                PreCandidate p=new PreCandidate();p.instrument=ins;p.ltp=l;p.ohlc=o;p.dayPct=day;\n                p.preScore=day*4.0+Math.max(0,2.50-nearHigh)*2.5+Math.max(0,fromOpen)*1.5;''',
'''if(l<20||l>10000||day<-0.60||day>9.0)continue;\n                double fromOpen=(l/o.open-1.0)*100.0; double nearHigh=o.high>0?(o.high-l)/l*100.0:9;\n                double recoveryPct=o.low>0?(l/o.low-1.0)*100.0:0; boolean crossedGreen=o.low<o.close*0.998&&l>o.close*1.0005;\n                if(fromOpen<-0.60||nearHigh>4.00)continue;\n                PreCandidate p=new PreCandidate();p.instrument=ins;p.ltp=l;p.ohlc=o;p.dayPct=day;p.fromOpenPct=fromOpen;p.recoveryPct=recoveryPct;p.crossedGreen=crossedGreen;\n                p.preScore=day*3.5+Math.max(0,3.00-nearHigh)*2.2+Math.max(0,fromOpen)*1.4+(crossedGreen?8.0:0)+Math.min(6.0,Math.max(0,recoveryPct-1.0)*1.4);''')

must_replace(sp,
'''double wickRatio=body>0?upper/body:2.0;\n        // WATCH/discovery gate only. Actual BUY remains governed by the much stricter hard gate in score().\n        if(entry<vwap*0.998||rsi<46||rsi>79||oneHour<-0.15||relVol<0.75||roomR2<0.20||distR1>0.80||distR1<-1.20||wickRatio>2.6)return null;\n        FeatureCandidate f=new FeatureCandidate();f.instrument=p.instrument;f.entry=entry;f.rsi=rsi;f.relVol=relVol;f.macd=macd;f.atr=atr;f.oneHour=oneHour;f.vwap=vwap;f.r1=levels.r1;f.r2=levels.r2;f.distR1=distR1;f.roomR2=roomR2;f.wickRatio=wickRatio;f.dayPct=p.dayPct;\n        f.baseScore=35 + Math.min(14,Math.max(0,oneHour*5)) + Math.min(12,Math.max(0,(relVol-1)*8)) + (entry>vwap?9:0) + (macd.hist>0&&macd.hist>macd.prevHist?10:4) + Math.max(0,8-Math.abs(rsi-62)*0.7) + Math.max(0,8-Math.abs(distR1)*8) + Math.min(8,Math.max(0,roomR2*5));''',
'''double wickRatio=body>0?upper/body:2.0;\n        TradeSetupLogic.Signals path=TradeSetupLogic.analyze(candles,p.ohlc,entry);\n        boolean recoveryDiscovery=path.crossedGreen&&path.recoveryPct>=1.0&&entry>=vwap*0.995;\n        // Discovery is wider than BUY qualification so the app can rank recoveries and fresh momentum without forcing trades.\n        if(entry<vwap*0.996||rsi<44||rsi>80||oneHour<-0.35||relVol<0.60||roomR2<0.15||distR1>1.10||distR1<-1.50||wickRatio>3.0)return null;\n        if(!macd.bullish&&!recoveryDiscovery&&macd.hist<macd.prevHist)return null;\n        FeatureCandidate f=new FeatureCandidate();f.instrument=p.instrument;f.entry=entry;f.rsi=rsi;f.relVol=relVol;f.macd=macd;f.atr=atr;f.oneHour=oneHour;f.vwap=vwap;f.r1=levels.r1;f.r2=levels.r2;f.distR1=distR1;f.roomR2=roomR2;f.wickRatio=wickRatio;f.dayPct=p.dayPct;\n        f.sessionHod=path.sessionHod;f.hodDistancePct=path.hodDistancePct;f.hodDrawdownPct=path.hodDrawdownPct;f.recoveryPct=path.recoveryPct;f.fromOpenPct=path.fromOpenPct;f.crossedGreen=path.crossedGreen;f.breakoutConfirmed=path.breakoutConfirmed;f.freshHodPressure=path.freshHodPressure;f.hodRejected=path.hodRejected;\n        f.baseScore=35 + Math.min(14,Math.max(0,oneHour*5)) + Math.min(12,Math.max(0,(relVol-1)*8)) + (entry>vwap?9:0) + (macd.hist>0&&macd.hist>macd.prevHist?10:4) + Math.max(0,8-Math.abs(rsi-62)*0.7) + Math.max(0,8-Math.abs(distR1)*8) + Math.min(8,Math.max(0,roomR2*5)) + (path.crossedGreen?6:0) + (path.freshHodPressure?4:0) - (path.hodRejected?8:0);''')

must_replace(sp,
'''// LIVE BUY hard gate: intentionally unchanged by the wider discovery universe.\n        boolean hard=entry>f.vwap && f.rsi>=55 && f.rsi<=72 && f.relVol>=1.30 && f.macd.hist>0 && f.macd.hist>=f.macd.prevHist && f.oneHour>=0.45 && f.oneHour<=4.0 && spreadPct<=0.22 && turnover>=50_000_000d && roomR2>=0.68 && distR1>=-0.55 && distR1<=0.38 && circuitRoom>=0.80;\n        double liquidity=Math.min(1.0,turnover/300_000_000d); double market=AdaptiveModel.clamp((breadth-40)/35.0,0,1);''',
'''double indicativeTarget=GrowwApi.roundToTick(entry*1.0070,f.instrument.tick,true);\n        boolean momentumHard=entry>f.vwap && f.rsi>=55 && f.rsi<=72 && f.relVol>=1.30 && f.macd.hist>0 && f.macd.hist>=f.macd.prevHist && f.oneHour>=0.45 && f.oneHour<=4.0 && spreadPct<=0.22 && turnover>=50_000_000d && roomR2>=0.68 && distR1>=-0.55 && distR1<=0.38 && circuitRoom>=0.80;\n        boolean recoveryHard=entry>f.vwap && TradeSetupLogic.recoverySetup(f.crossedGreen,f.recoveryPct,f.fromOpenPct,f.rsi,f.relVol,f.macd.hist,f.macd.prevHist,f.oneHour,spreadPct,turnover,roomR2,circuitRoom,breadth,depthRatio);\n        boolean clearPath=TradeSetupLogic.clearPath(entry,indicativeTarget,f.sessionHod,f.hodRejected,f.breakoutConfirmed,f.freshHodPressure);\n        boolean hard=(momentumHard||recoveryHard)&&clearPath;\n        double liquidity=Math.min(1.0,turnover/300_000_000d); double market=AdaptiveModel.clamp((breadth-40)/35.0,0,1);''')

must_replace(sp,
'''JSONObject features=new JSONObject(); try{features.put("vwap",entry>f.vwap?1:0);features.put("rsi",rsiQuality);features.put("relvol",rel);features.put("macd",f.macd.hist>=f.macd.prevHist?1:0);features.put("momentum",mom);features.put("breakout",breakout);features.put("liquidity",liquidity);features.put("market",market);features.put("depth",depthRatio);features.put("range",range);\n            LocalTime scanTime=LocalDateTime.now(IST).toLocalTime(); double timeQuality=scanTime.isBefore(LocalTime.of(10,30))?1.0:scanTime.isBefore(LocalTime.of(12,0))?0.85:scanTime.isBefore(LocalTime.of(14,0))?0.70:0.45;features.put("time",timeQuality);}catch(Exception ignore){}''',
'''JSONObject features=new JSONObject(); try{features.put("vwap",entry>f.vwap?1:0);features.put("rsi",rsiQuality);features.put("relvol",rel);features.put("macd",f.macd.hist>=f.macd.prevHist?1:0);features.put("momentum",mom);features.put("breakout",breakout);features.put("liquidity",liquidity);features.put("market",market);features.put("depth",depthRatio);features.put("range",range);\n            double hodRoom=TradeSetupLogic.roomBeyondTargetPct(indicativeTarget,f.sessionHod);features.put("hodroom",TradeSetupLogic.clamp((hodRoom+0.20)/1.20,0,1));features.put("recovery",TradeSetupLogic.clamp(f.recoveryPct/5.0,0,1));features.put("rejection",f.hodRejected&&!f.breakoutConfirmed?0:1);\n            features.put("setupType",recoveryHard?"RECOVERY":(f.breakoutConfirmed||f.freshHodPressure?"HOD MOMENTUM":"MOMENTUM"));features.put("sessionHod",f.sessionHod);features.put("hodDistancePct",f.hodDistancePct);features.put("hodDrawdownPct",f.hodDrawdownPct);features.put("hodRoomAfterTargetPct",hodRoom);features.put("hodRejected",f.hodRejected);features.put("clearPath",clearPath);features.put("recoveryPct",f.recoveryPct);features.put("crossedGreen",f.crossedGreen);features.put("breakoutConfirmed",f.breakoutConfirmed);\n            LocalTime scanTime=LocalDateTime.now(IST).toLocalTime(); double timeQuality=scanTime.isBefore(LocalTime.of(10,30))?1.0:scanTime.isBefore(LocalTime.of(12,0))?0.85:scanTime.isBefore(LocalTime.of(14,0))?0.70:0.45;features.put("time",timeQuality);}catch(Exception ignore){}''')

must_replace(sp,
'''double score=f.baseScore + Math.min(8,liquidity*8) + Math.max(-4,Math.min(5,(depthRatio-0.5)*12)) - Math.max(0,(spreadPct-0.08)*20) - Math.max(0,(f.rsi-68)*1.6) - Math.max(0,(f.wickRatio-0.7)*3);''',
'''double score=f.baseScore + Math.min(8,liquidity*8) + Math.max(-4,Math.min(5,(depthRatio-0.5)*12)) - Math.max(0,(spreadPct-0.08)*20) - Math.max(0,(f.rsi-68)*1.6) - Math.max(0,(f.wickRatio-0.7)*3) + (recoveryHard?5:0) + (f.breakoutConfirmed?4:0) - (f.hodRejected&&!f.breakoutConfirmed?10:0) - (!clearPath?12:0);''')

must_replace(sp,
'''double grossPct=0.70; double target=GrowwApi.roundToTick(entry*(1+grossPct/100.0),f.instrument.tick,true);''',
'''double target=indicativeTarget;''')

must_replace(sp,
'''private String reason(Recommendation r,boolean hard,int minScore,int n){\n        if(r.qualified)return "QUALIFIED • VWAP + momentum + volume + R1/R2 room + liquidity aligned";\n        List<String>x=new ArrayList<>();if(!hard)x.add("hard gates not fully aligned");if(r.score<minScore)x.add("score < "+minScore);if(n>=30&&r.probability<0.80)x.add("learned probability < 80%");if(n<30)x.add("model still calibrating");return "WATCH • "+String.join(" • ",x);\n    }''',
'''private String reason(Recommendation r,boolean hard,int minScore,int n){\n        String setup=r.features.optString("setupType","MOMENTUM");\n        if(r.qualified)return "QUALIFIED • "+setup+" • clear path to target + volume/VWAP/liquidity aligned";\n        List<String>x=new ArrayList<>();if(!r.features.optBoolean("clearPath",true))x.add("HOD/resistance blocks target");else if(!hard)x.add("hard gates not fully aligned");if(r.features.optBoolean("hodRejected",false))x.add("prior HOD rejection detected");if(r.score<minScore)x.add("score < "+minScore);if(n>=30&&r.probability<0.80)x.add("learned probability < 80%");if(n<30)x.add("model still calibrating");return "WATCH • "+setup+" • "+String.join(" • ",x);\n    }''')

must_replace(sp,
'''static final class PreCandidate { Instrument instrument;GrowwApi.Ohlc ohlc;double ltp,dayPct,preScore; }\n    static final class FeatureCandidate { Instrument instrument;GrowwApi.Quote quote;Indicators.Macd macd;double entry,rsi,relVol,atr,oneHour,vwap,r1,r2,distR1,roomR2,wickRatio,dayPct,baseScore; }''',
'''static final class PreCandidate { Instrument instrument;GrowwApi.Ohlc ohlc;double ltp,dayPct,preScore,fromOpenPct,recoveryPct;boolean crossedGreen; }\n    static final class FeatureCandidate { Instrument instrument;GrowwApi.Quote quote;Indicators.Macd macd;double entry,rsi,relVol,atr,oneHour,vwap,r1,r2,distR1,roomR2,wickRatio,dayPct,baseScore,sessionHod,hodDistancePct,hodDrawdownPct,recoveryPct,fromOpenPct;boolean crossedGreen,breakoutConfirmed,freshHodPressure,hodRejected; }''')

# ---------------- Adaptive model: learn HOD/recovery features without breaking old saved weights ----------------
lp=ROOT/'LearningStore.java'
must_replace(lp,
'''static final String[] NAMES={"vwap","rsi","relvol","macd","momentum","breakout","liquidity","market","depth","range","time"};\n    private static final double[] DEFAULT={0.92,0.55,0.78,0.72,0.62,0.58,0.68,0.55,0.35,0.35,0.45};''',
'''static final String[] NAMES={"vwap","rsi","relvol","macd","momentum","breakout","liquidity","market","depth","range","time","hodroom","recovery","rejection"};\n    private static final double[] DEFAULT={0.92,0.55,0.78,0.72,0.62,0.58,0.68,0.55,0.35,0.35,0.45,0.62,0.52,0.68};''')

# ---------------- UI: explicit accuracy score + setup/path evidence ----------------
mp=ROOT/'MainActivity.java'
must_replace(mp,'5-minute adaptive intraday engine • 30-minute horizon','5-minute adaptive intraday engine • HOD-aware • 30-minute horizon')
must_replace(mp,'TextView cap=txt("30-MIN TARGET HIT RATE",11,MUTED,true);','TextView cap=txt("ACCURACY SCORE • 30-MIN",11,MUTED,true);')
must_replace(mp,
'''c.addView(txt(String.format(Locale.US,"Score %.0f/100  •  model %.0f%%  •  max 30 min",r.score,r.probability*100),12,MUTED,false));c.addView(space(8));''',
'''String setup=r.features.optString("setupType","MOMENTUM");double hod=r.features.optDouble("sessionHod",0);double hodRoom=r.features.optDouble("hodRoomAfterTargetPct",9);double recov=r.features.optDouble("recoveryPct",0);\n            c.addView(txt(String.format(Locale.US,"Score %.0f/100  •  model %.0f%%  •  max 30 min",r.score,r.probability*100),12,MUTED,false));\n            c.addView(txt("Setup "+setup+" • prior HOD "+(hod>0?("₹"+money(hod)):"—")+" • target-clearance "+String.format(Locale.US,"%+.2f%%",hodRoom)+" • recovery "+String.format(Locale.US,"%.2f%%",recov),11,r.features.optBoolean("clearPath",true)?MUTED:RED,false));c.addView(space(8));''')
must_replace(mp,
'''Every recommendation is replayed for 30 minutes. Target-before-stop = success; stop/timeout = failure; same-candle target+stop is excluded as ambiguous. Learning may tighten selection, but cannot change the 0.50% net target, 30-minute time stop, liquidity gates, or protection rules.''',
'''Every BUY-qualified call is replayed for 30 minutes and shadow candidates train at lower weight. v1.2 also learns recovery-from-negative, HOD rejection, breakout confirmation and clear-path-to-target behaviour. Learning may tighten selection, but cannot change the 0.50% net target, 30-minute time stop, liquidity gates, or protection rules.''')
must_replace(mp,'v1.1.0 • standalone package com.suhas.nseunifiedscanner','v1.2.0 • standalone package com.suhas.nseunifiedscanner')

# ---------------- Service: heads-up BUY alerts, deduplicated and actionable ----------------
up=ROOT/'UnifiedService.java'
must_replace(up,
'''private static final int NOTIFY_ID=27101; private static final String CHANNEL="nse_scanner_live";''',
'''private static final int NOTIFY_ID=27101; private static final String CHANNEL="nse_scanner_live"; private static final String ALERT_CHANNEL="nse_scanner_buy_alerts_v12";''')

must_replace(up,
'''checkStaticIp(false);\n                setStatus("Scan complete • "+r.marketLabel+" • "+r.recommendations.size()+" candidates");''',
'''checkStaticIp(false);\n                notifyQualifiedSetups(r);\n                setStatus("Scan complete • "+r.marketLabel+" • "+r.recommendations.size()+" candidates");''')

insert='''    private void notifyQualifiedSetups(ScannerEngine.ScanResult r){\n        if(r==null||r.recommendations==null||r.recommendations.isEmpty()||ActiveTrade.load(this)!=null)return;\n        LocalTime t=LocalDateTime.now(ScannerEngine.IST).toLocalTime();if(t.isBefore(LocalTime.of(9,15))||t.isAfter(LocalTime.of(14,40)))return;\n        if(prefs().getInt("static_ip_state",0)!=1)return;\n        NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);long now=System.currentTimeMillis();int emitted=0;\n        for(ScannerEngine.Recommendation rec:r.recommendations){\n            if(!rec.qualified)continue;String key="buy_alert_"+rec.symbol;long last=prefs().getLong(key,0);if(now-last<25*60_000L)continue;\n            prefs().edit().putLong(key,now).apply();Intent open=new Intent(this,MainActivity.class);open.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TOP);\n            PendingIntent pi=PendingIntent.getActivity(this,Math.abs(rec.symbol.hashCode()),open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);\n            String setup=rec.features.optString("setupType","MOMENTUM");String body=String.format(Locale.US,"%s • Entry ₹%.2f • Target ₹%.2f • SL ₹%.2f • Score %.0f/100 • model %.0f%% • max 30 min. Tap to review and BUY.",setup,rec.entry,rec.target,rec.stop,rec.score,rec.probability*100);\n            Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,ALERT_CHANNEL):new Notification.Builder(this);\n            b.setContentTitle("BUY SETUP • "+rec.symbol).setContentText(String.format(Locale.US,"Entry ₹%.2f • Target ₹%.2f • SL ₹%.2f",rec.entry,rec.target,rec.stop)).setStyle(new Notification.BigTextStyle().bigText(body)).setSmallIcon(android.R.drawable.ic_input_add).setContentIntent(pi).setAutoCancel(true).setCategory(Notification.CATEGORY_RECOMMENDATION).setWhen(now);\n            if(Build.VERSION.SDK_INT<26)b.setPriority(Notification.PRIORITY_HIGH).setDefaults(Notification.DEFAULT_ALL);\n            nm.notify(33000+Math.abs(rec.symbol.hashCode()%5000),b.build());learning.audit("ALERT",rec.symbol+" BUY-qualified notification sent");if(++emitted>=3)break;\n        }\n    }\n\n'''
must_replace(up,'    private void checkStaticIp(boolean force){',insert+'    private void checkStaticIp(boolean force){')
must_replace(up,'NSEUnifiedScanner/1.1','NSEUnifiedScanner/1.2')
must_replace(up,
'''private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"NSE Unified Scanner",NotificationManager.IMPORTANCE_LOW);c.setDescription("5-minute NSE scans and active intraday protection");((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}}''',
'''private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);NotificationChannel c=new NotificationChannel(CHANNEL,"NSE Unified Scanner",NotificationManager.IMPORTANCE_LOW);c.setDescription("5-minute NSE scans and active intraday protection");nm.createNotificationChannel(c);NotificationChannel a=new NotificationChannel(ALERT_CHANNEL,"NSE BUY-qualified alerts",NotificationManager.IMPORTANCE_HIGH);a.setDescription("Heads-up alerts only for newly BUY-qualified scanner setups");a.enableVibration(true);nm.createNotificationChannel(a);}}''')

print('v1.2 patch applied successfully')
