from pathlib import Path
import re

ROOT=Path('unified-scanner/app/src/main/java/com/suhas/nseunifiedscanner')
TEST=Path('unified-scanner/app/src/test/java/com/suhas/nseunifiedscanner')
sp=ROOT/'ScannerEngine.java'; lp=ROOT/'LearningStore.java'; ip=ROOT/'LearningInsights.java'; mp=ROOT/'MainActivity.java'; gp=Path('unified-scanner/app/build.gradle')

def must(path, old, new):
    p=Path(path); s=p.read_text()
    if old not in s: raise SystemExit(f'v1.6.4 anchor missing in {p}: {old[:220]!r}')
    p.write_text(s.replace(old,new,1))

def opt(path, old, new):
    p=Path(path); s=p.read_text()
    if old in s: p.write_text(s.replace(old,new,1))

# ---------------------------------------------------------------------------
# Two-stage forward confirmation and momentum-decay protection.
# ---------------------------------------------------------------------------
(ROOT/'ForwardConfirmationLogic.java').write_text('''package com.suhas.nseunifiedscanner;\n\n/** Pure 1-minute confirmation logic: pressure must persist instead of flashing once. */\nfinal class ForwardConfirmationLogic {\n    private ForwardConfirmationLogic(){}\n    static boolean persistence(double lastClose,double prevClose,double lastLow,double prevLow,double lastVol,double prevVol,double prev2Vol,boolean macdAccel,boolean higherLows,double price3mPct,double microBreakoutPct){\n        if(!(lastClose>0)||!(prevClose>0))return false;\n        double prevAvg=Math.max(0,(Math.max(0,prevVol)+Math.max(0,prev2Vol))/2.0);\n        boolean volumeHolds=prevAvg<=0 || lastVol>=prevAvg*0.55;\n        boolean priceHolds=lastClose>=prevClose*0.9985 && (!(prevLow>0)||lastLow>=prevLow*0.9975);\n        boolean trigger=price3mPct>=0.03 || microBreakoutPct>=-0.08 || (macdAccel&&higherLows);\n        return volumeHolds && priceHolds && trigger && (macdAccel||higherLows);\n    }\n    static boolean momentumDecay(double currentAccel,double previousAccel,double price3mPct,double lastClose,double prevClose){\n        boolean volumeCollapse=previousAccel>=1.35 && currentAccel<Math.max(0.85,previousAccel*0.60);\n        boolean priceFade=price3mPct<-0.15 || (lastClose>0&&prevClose>0&&lastClose<prevClose*0.9970);\n        return volumeCollapse || (priceFade && currentAccel<1.10);\n    }\n}\n''')
(TEST/'ForwardConfirmationLogicTest.java').write_text('''package com.suhas.nseunifiedscanner;\nimport org.junit.Test;\nimport static org.junit.Assert.*;\npublic class ForwardConfirmationLogicTest {\n @Test public void persistentPressurePasses(){assertTrue(ForwardConfirmationLogic.persistence(100.12,100.08,99.98,99.95,1800,2000,1700,true,true,0.11,-0.03));}\n @Test public void collapsingLastMinuteVolumeFailsPersistence(){assertFalse(ForwardConfirmationLogic.persistence(100.10,100.08,99.98,99.95,400,2000,1800,true,true,0.10,-0.02));}\n @Test public void sharpAccelerationCollapseIsDecay(){assertTrue(ForwardConfirmationLogic.momentumDecay(0.82,2.20,0.05,100.1,100.0));}\n @Test public void stableAccelerationIsNotDecay(){assertFalse(ForwardConfirmationLogic.momentumDecay(1.70,1.90,0.08,100.1,100.0));}\n}\n''')

# Pattern-memory logic is intentionally separate from the adaptive logistic weights.
(ROOT/'PatternMemoryLogic.java').write_text('''package com.suhas.nseunifiedscanner;\n\nimport java.util.List;\n\nfinal class PatternMemoryLogic {\n    private PatternMemoryLogic(){}\n    static final class Snapshot {\n        String setup=""; double early,volAccel,rsi,breadth,weight=1.0; boolean hodRejected,hit;\n    }\n    static final class Evidence {\n        int n,hits; double posterior; boolean veto,strong;\n        Evidence(int n,int hits,double posterior){this.n=n;this.hits=hits;this.posterior=posterior;veto=n>=10&&posterior<0.36;strong=n>=12&&posterior>=0.55;}\n    }\n    static Evidence evaluate(String setup,double early,double volAccel,double rsi,double breadth,boolean hodRejected,List<Snapshot> history){\n        int n=0,hits=0;double wn=0,wh=0;String regime=regime(breadth);\n        if(history!=null)for(Snapshot s:history){\n            int sim=0;if(norm(setup).equals(norm(s.setup)))sim+=2;if(regime.equals(regime(s.breadth)))sim++;if(Math.abs(early-s.early)<=12.0)sim++;\n            double a=Math.max(0.15,volAccel),b=Math.max(0.15,s.volAccel);if(Math.abs(Math.log(a/b))<=Math.log(1.90))sim++;\n            boolean rsiKnown=rsi>0&&s.rsi>0;if(rsiKnown&&Math.abs(rsi-s.rsi)<=8.0)sim++;if(hodRejected==s.hodRejected)sim++;\n            int need=rsiKnown?5:4;if(sim<need)continue;n++;if(s.hit)hits++;double w=Math.max(0.25,Math.min(2.0,s.weight));wn+=w;if(s.hit)wh+=w;\n        }\n        // Beta(2,3) prior = 40%; enough to avoid overreacting to tiny buckets.\n        double post=(wh+2.0)/(wn+5.0);return new Evidence(n,hits,post);\n    }\n    static String regime(double breadth){return breadth>=60?"BULL":breadth<=40?"WEAK":"MIXED";}\n    private static String norm(String s){return s==null?"":s.trim().toUpperCase();}\n}\n''')
(TEST/'PatternMemoryLogicTest.java').write_text('''package com.suhas.nseunifiedscanner;\nimport java.util.*;import org.junit.Test;import static org.junit.Assert.*;\npublic class PatternMemoryLogicTest {\n private PatternMemoryLogic.Snapshot s(boolean hit){PatternMemoryLogic.Snapshot x=new PatternMemoryLogic.Snapshot();x.setup="PRE-SPIKE";x.early=88;x.volAccel=1.8;x.rsi=56;x.breadth=66;x.hodRejected=false;x.hit=hit;return x;}\n @Test public void weakRepeatedPatternVetoes(){List<PatternMemoryLogic.Snapshot>a=new ArrayList<>();for(int i=0;i<12;i++)a.add(s(i<2));PatternMemoryLogic.Evidence e=PatternMemoryLogic.evaluate("PRE-SPIKE",90,1.7,55,68,false,a);assertTrue(e.veto);}\n @Test public void strongPatternIsFlagged(){List<PatternMemoryLogic.Snapshot>a=new ArrayList<>();for(int i=0;i<14;i++)a.add(s(i<11));PatternMemoryLogic.Evidence e=PatternMemoryLogic.evaluate("PRE-SPIKE",90,1.7,55,68,false,a);assertTrue(e.strong);assertFalse(e.veto);}\n @Test public void tinySampleDoesNotVeto(){List<PatternMemoryLogic.Snapshot>a=new ArrayList<>();for(int i=0;i<5;i++)a.add(s(false));PatternMemoryLogic.Evidence e=PatternMemoryLogic.evaluate("PRE-SPIKE",90,1.7,55,68,false,a);assertFalse(e.veto);}\n}\n''')

# ---------------------------------------------------------------------------
# LearningInsights: expose recent resolved pattern memory (shadow + primary).
# ---------------------------------------------------------------------------
insert='''\n    synchronized List<PatternMemoryLogic.Snapshot> recentPatternSamples(int limit){\n        List<PatternMemoryLogic.Snapshot> out=new ArrayList<>();int lim=Math.max(50,Math.min(1500,limit));\n        try(SQLiteDatabase db=open();Cursor c=db.rawQuery("SELECT status,features FROM shadow_samples WHERE status IN ('SUCCESS','FAIL','TIMEOUT') ORDER BY resolved_ms DESC LIMIT "+lim,null)){\n            while(c.moveToNext()){PatternMemoryLogic.Snapshot s=patternSnapshot(c.getString(0),c.getString(1),1.0);if(s!=null)out.add(s);}\n        }catch(Exception ignore){}\n        try(SQLiteDatabase db=open();Cursor c=db.rawQuery("SELECT status,features FROM recommendations WHERE status IN ('SUCCESS','FAIL','TIMEOUT') ORDER BY resolved_ms DESC LIMIT 120",null)){\n            while(c.moveToNext()){PatternMemoryLogic.Snapshot s=patternSnapshot(c.getString(0),c.getString(1),1.75);if(s!=null)out.add(s);}\n        }catch(Exception ignore){}\n        return out;\n    }\n\n    private static PatternMemoryLogic.Snapshot patternSnapshot(String status,String raw,double weight){\n        try{JSONObject f=new JSONObject(raw);PatternMemoryLogic.Snapshot s=new PatternMemoryLogic.Snapshot();s.setup=f.optString("setupType","");s.early=f.optDouble("earlyPressure",0);s.volAccel=f.optDouble("volumeAccel",0);s.rsi=f.optDouble("rsi1m",0);s.breadth=f.optDouble("breadthPct",0);s.hodRejected=f.optBoolean("hodRejected",false);s.hit="SUCCESS".equals(status);s.weight=weight;return s;}catch(Exception e){return null;}\n    }\n\n'''
must(ip,'    synchronized PipelineStats pipelineStats(){',insert+'    synchronized PipelineStats pipelineStats(){')

# ---------------------------------------------------------------------------
# Scanner: use 1-minute persistence + decay + pattern memory + proper entry cutoff.
# ---------------------------------------------------------------------------
must(sp,
'''            LearningStore.Stats stats=learning.stats();\n            LocalDateTime microEnd=LocalDateTime.now(IST).minusMinutes(1).withSecond(59).withNano(0);LocalDateTime microStart=microEnd.minusMinutes(95);\n''',
'''            LearningStore.Stats stats=learning.stats();List<PatternMemoryLogic.Snapshot> patternHistory=insights.recentPatternSamples(1000);\n            LocalDateTime microEnd=LocalDateTime.now(IST).minusMinutes(1).withSecond(59).withNano(0);LocalDateTime microStart=microEnd.minusMinutes(95);\n''')
must(sp,
'''                Recommendation r=score(fc,result.breadth,minScore,stats.n); if(r!=null)recs.add(r);\n''',
'''                Recommendation r=score(fc,result.breadth,minScore,stats.n,patternHistory); if(r!=null)recs.add(r);\n''')
must(sp,
'''    private Recommendation score(FeatureCandidate f,double breadth,int minScore,int modelN){\n''',
'''    private Recommendation score(FeatureCandidate f,double breadth,int minScore,int modelN,List<PatternMemoryLogic.Snapshot> patternHistory){\n''')

# Calculate previous 3-minute acceleration, persistence and decay from the micro candles.
must(sp,
'''        double rsi1=Indicators.rsi(close,14);Indicators.Macd m1=Indicators.macd(close);boolean macdAccel=m1.hist>=m1.prevHist;boolean higherLows=low[n-1]>=low[n-3]&&low[n-3]>=low[n-5];\n        PreSpikeLogic.Assessment a=PreSpikeLogic.assess(price3,price5,extension10,lastRange,f.dayPct,vwapDist,volAccel,rsi1,macdAccel,higherLows,compression,microBreakout);\n        f.earlyPressure=a.pressure;f.preSpike=a.preSpike;f.lateSpike=a.lateSpike;f.price3mPct=price3;f.price5mPct=price5;f.extension10mPct=extension10;f.volumeAccel=volAccel;f.compressionPct=compression;f.microBreakoutPct=microBreakout;f.rsi1m=rsi1;f.macd1mAccel=macdAccel;f.higherLows=higherLows;\n''',
'''        double rsi1=Indicators.rsi(close,14);Indicators.Macd m1=Indicators.macd(close);boolean macdAccel=m1.hist>=m1.prevHist;boolean higherLows=low[n-1]>=low[n-3]&&low[n-3]>=low[n-5];\n        double prev3=0;for(int i=Math.max(0,n-6);i<=n-4;i++)prev3+=vol[i];prev3/=3.0;double prevBase=0;int pbc=0;for(int i=Math.max(0,n-18);i<n-6;i++){prevBase+=vol[i];pbc++;}prevBase=pbc>0?prevBase/pbc:0;double prevAccel=prevBase>0?prev3/prevBase:0;\n        boolean persistent=ForwardConfirmationLogic.persistence(close[n-1],close[n-2],low[n-1],low[n-2],vol[n-1],vol[n-2],vol[n-3],macdAccel,higherLows,price3,microBreakout);\n        boolean decay=ForwardConfirmationLogic.momentumDecay(volAccel,prevAccel,price3,close[n-1],close[n-2]);\n        PreSpikeLogic.Assessment a=PreSpikeLogic.assess(price3,price5,extension10,lastRange,f.dayPct,vwapDist,volAccel,rsi1,macdAccel,higherLows,compression,microBreakout);\n        f.earlyPressure=a.pressure;f.preSpike=a.preSpike;f.lateSpike=a.lateSpike;f.price3mPct=price3;f.price5mPct=price5;f.extension10mPct=extension10;f.volumeAccel=volAccel;f.prevVolumeAccel=prevAccel;f.compressionPct=compression;f.microBreakoutPct=microBreakout;f.rsi1m=rsi1;f.macd1mAccel=macdAccel;f.higherLows=higherLows;f.persistenceConfirmed=persistent;f.momentumDecay=decay;\n''')

must(sp,
'''        boolean clearPath=classicClearPath||bullishHodBreakout;\n        boolean hard=(preSpikeHard||recoveryHard||volumeBuildHard||relativeStrengthHard||bullishHodBreakout)&&clearPath&&!f.lateSpike;\n''',
'''        boolean clearPath=classicClearPath||bullishHodBreakout;\n        boolean confirmationPass=(f.persistenceConfirmed||(f.breakoutConfirmed&&f.volumeAccel>=2.0))&&!f.momentumDecay;\n        boolean hard=(preSpikeHard||recoveryHard||volumeBuildHard||relativeStrengthHard||bullishHodBreakout)&&clearPath&&!f.lateSpike;\n''')

must(sp,
'''            features.put("spreadKnown",spreadKnown);features.put("spreadSource",q.spreadSource);double capQuality=q.marketCap>0?TradeSetupLogic.clamp((Math.log10(Math.max(1,q.marketCap))-9.0)/2.5,0,1):0.5;features.put("capquality",capQuality);''',
'''            features.put("spreadKnown",spreadKnown);features.put("spreadSource",q.spreadSource);features.put("rsi1m",f.rsi1m);features.put("prevVolumeAccel",f.prevVolumeAccel);features.put("confirmation",confirmationPass?1:0);features.put("decaysafe",f.momentumDecay?0:1);features.put("persistenceConfirmed",f.persistenceConfirmed);features.put("momentumDecay",f.momentumDecay);double capQuality=q.marketCap>0?TradeSetupLogic.clamp((Math.log10(Math.max(1,q.marketCap))-9.0)/2.5,0,1):0.5;features.put("capquality",capQuality);''')

must(sp,
'''        double probability=AdaptiveModel.predict(context,features);\n        double spreadPenalty=spreadKnown?Math.max(0,(spreadPct-0.08)*20):10.0;double capBonus=q.marketCap>0?Math.max(-2,Math.min(3,(Math.log10(Math.max(1,q.marketCap))-9.0)*1.5)):0;\n''',
'''        PatternMemoryLogic.Evidence pattern=PatternMemoryLogic.evaluate(features.optString("setupType",""),f.earlyPressure,f.volumeAccel,f.rsi1m,breadth,f.hodRejected,patternHistory);boolean patternVeto=pattern.veto,patternStrong=pattern.strong;boolean tradableWindow=entryWindowNow();try{features.put("patternN",pattern.n);features.put("patternHits",pattern.hits);features.put("patternRate",pattern.posterior);features.put("patternVeto",patternVeto);features.put("patternStrong",patternStrong);features.put("tradableWindow",tradableWindow);features.put("patternedge",pattern.posterior);}catch(Exception ignore){}\n        double probability=AdaptiveModel.predict(context,features);\n        double spreadPenalty=spreadKnown?Math.max(0,(spreadPct-0.08)*20):10.0;double capBonus=q.marketCap>0?Math.max(-2,Math.min(3,(Math.log10(Math.max(1,q.marketCap))-9.0)*1.5)):0;\n''')

must(sp,
'''        double score=f.baseScore + f.earlyPressure*0.22 + Math.min(7,liquidity*7) + Math.max(-4,Math.min(5,(depthRatio-0.5)*12)) - spreadPenalty + capBonus + (recoveryHard?5:0) + (volumeBuildHard?5:0) + (relativeStrengthHard?4:0) + (bullishHodBreakout?7:0) + (f.higherLows?3:0) - (f.hodRejected&&!f.breakoutConfirmed?10:0) - (!clearPath?12:0) - (f.lateSpike?38:0);\n''',
'''        double score=f.baseScore + f.earlyPressure*0.22 + Math.min(7,liquidity*7) + Math.max(-4,Math.min(5,(depthRatio-0.5)*12)) - spreadPenalty + capBonus + (recoveryHard?5:0) + (volumeBuildHard?5:0) + (relativeStrengthHard?4:0) + (bullishHodBreakout?7:0) + (f.higherLows?3:0) + (confirmationPass?5:-7) + (patternStrong?5:0) - (patternVeto?12:0) - (f.momentumDecay?18:0) - (f.hodRejected&&!f.breakoutConfirmed?10:0) - (!clearPath?12:0) - (f.lateSpike?38:0);\n''')

must(sp,
'''        int effectiveMin=modelN<30?Math.min(minScore,74):(modelN<60?Math.min(minScore,78):minScore);double modelGate=modelN<30?0.0:(modelN<60?0.58:0.68);boolean qualified=hard && score>=effectiveMin && (modelN<30||probability>=modelGate);\n''',
'''        int effectiveMin=modelN<30?Math.min(minScore,74):(modelN<60?Math.min(minScore,78):minScore);double modelGate=modelN<30?0.0:(modelN<60?0.58:0.68);boolean qualified=hard && confirmationPass && !patternVeto && tradableWindow && score>=effectiveMin && (modelN<30||probability>=modelGate);\n''')

must(sp,
'''        if(r.qualified&&r.features.optBoolean("bullishHodBreakout",false))return "QUALIFIED • BULLISH HOD BREAKOUT • early pressure + volume + bullish breadth confirmed through prior HOD";\n        if(r.qualified)return "QUALIFIED • "+setup+" • clear path to target + volume/VWAP/liquidity aligned";\n        if(!r.features.optBoolean("spreadKnown",false))return "WATCH • "+setup+" • SPREAD UNKNOWN — Groww top bid/offer and market depth unavailable; BUY blocked safely";\n''',
'''        if(r.qualified&&r.features.optBoolean("bullishHodBreakout",false))return "QUALIFIED • BULLISH HOD BREAKOUT • 2-stage confirmation + volume + breadth + pattern memory aligned";\n        if(r.qualified)return "QUALIFIED • "+setup+" • 2-stage 1m confirmation + clear path + pattern memory aligned";\n        if(!r.features.optBoolean("tradableWindow",true))return "WATCH • AFTER 14:40 ENTRY CUTOFF — shadow-learning only; excluded from tradable accuracy";\n        if(!r.features.optBoolean("spreadKnown",false))return "WATCH • "+setup+" • SPREAD UNKNOWN — Groww top bid/offer and market depth unavailable; BUY blocked safely";\n        if(r.features.optBoolean("momentumDecay",false))return "WATCH • "+setup+" • MOMENTUM DECAY — volume/price pressure faded before confirmation";\n        if(!r.features.optBoolean("confirmation",false))return "WATCH • "+setup+" • WAITING FOR 2-STAGE 1m CONFIRMATION";\n        if(r.features.optBoolean("patternVeto",false))return "WATCH • "+setup+" • PATTERN MEMORY VETO — similar resolved setups have insufficient forward hit-rate";\n''')

must(sp,
'''    static boolean marketHoursNow(){LocalDateTime n=LocalDateTime.now(IST);DayOfWeek d=n.getDayOfWeek();if(d==DayOfWeek.SATURDAY||d==DayOfWeek.SUNDAY)return false;LocalTime t=n.toLocalTime();return !t.isBefore(LocalTime.of(9,15))&&t.isBefore(LocalTime.of(15,11));}\n''',
'''    static boolean entryWindowNow(){LocalDateTime n=LocalDateTime.now(IST);DayOfWeek d=n.getDayOfWeek();if(d==DayOfWeek.SATURDAY||d==DayOfWeek.SUNDAY)return false;LocalTime t=n.toLocalTime();return !t.isBefore(LocalTime.of(9,15))&&!t.isAfter(LocalTime.of(14,40));}\n    static boolean marketHoursNow(){LocalDateTime n=LocalDateTime.now(IST);DayOfWeek d=n.getDayOfWeek();if(d==DayOfWeek.SATURDAY||d==DayOfWeek.SUNDAY)return false;LocalTime t=n.toLocalTime();return !t.isBefore(LocalTime.of(9,15))&&t.isBefore(LocalTime.of(15,11));}\n''')

must(sp,
'''    static final class FeatureCandidate { Instrument instrument;GrowwApi.Quote quote;Indicators.Macd macd;double entry,rsi,relVol,atr,oneHour,vwap,r1,r2,distR1,roomR2,wickRatio,dayPct,baseScore,sessionHod,hodDistancePct,hodDrawdownPct,recoveryPct,fromOpenPct,earlyPressure,price3mPct,price5mPct,extension10mPct,volumeAccel,compressionPct,microBreakoutPct,rsi1m;boolean crossedGreen,breakoutConfirmed,freshHodPressure,hodRejected,preSpike,lateSpike,macd1mAccel,higherLows; }\n''',
'''    static final class FeatureCandidate { Instrument instrument;GrowwApi.Quote quote;Indicators.Macd macd;double entry,rsi,relVol,atr,oneHour,vwap,r1,r2,distR1,roomR2,wickRatio,dayPct,baseScore,sessionHod,hodDistancePct,hodDrawdownPct,recoveryPct,fromOpenPct,earlyPressure,price3mPct,price5mPct,extension10mPct,volumeAccel,prevVolumeAccel,compressionPct,microBreakoutPct,rsi1m;boolean crossedGreen,breakoutConfirmed,freshHodPressure,hodRejected,preSpike,lateSpike,macd1mAccel,higherLows,persistenceConfirmed,momentumDecay; }\n''')

# ---------------------------------------------------------------------------
# Adaptive model learns confirmation/decay safety/pattern edge too.
# ---------------------------------------------------------------------------
must(lp,
'''    static final String[] NAMES={"vwap","rsi","relvol","macd","momentum","breakout","liquidity","market","depth","range","time","hodroom","recovery","rejection","earlypress","volaccel","compression","extension","bullregime","hodbreak","microsetup","capquality"};\n    private static final double[] DEFAULT={0.92,0.55,0.78,0.72,0.62,0.58,0.68,0.55,0.35,0.35,0.45,0.62,0.52,0.68,0.82,0.72,0.58,0.74,0.38,0.30,0.28,0.12};\n''',
'''    static final String[] NAMES={"vwap","rsi","relvol","macd","momentum","breakout","liquidity","market","depth","range","time","hodroom","recovery","rejection","earlypress","volaccel","compression","extension","bullregime","hodbreak","microsetup","capquality","confirmation","decaysafe","patternedge"};\n    private static final double[] DEFAULT={0.92,0.55,0.78,0.72,0.62,0.58,0.68,0.55,0.35,0.35,0.45,0.62,0.52,0.68,0.82,0.72,0.58,0.74,0.38,0.30,0.28,0.12,0.46,0.38,0.28};\n''')

# ---------------------------------------------------------------------------
# UI: today vs rolling accuracy + confirmation/pattern evidence.
# ---------------------------------------------------------------------------
s=mp.read_text()
s=s.replace('LinearLayout perf=card();TextView cap=txt("0.30% NET ACCURACY • 30-MIN",11,MUTED,true);','LinearLayout perf=card();TextView cap=txt("ROLLING 0.30% NET ACCURACY • 30-MIN",11,MUTED,true);')
s=s.replace('goal.addView(txt("10 is an opportunity goal, not a forced-trade quota. During the first 30 primary outcomes the model learns but does not veto technically valid setups; hard risk/path gates remain mandatory.",11,MUTED,false));','goal.addView(txt("10 is an opportunity goal, not a forced-trade quota. v1.6.4 requires 2-stage 1-minute persistence and can veto historically weak pattern buckets even during calibration.",11,MUTED,false));')
s=s.replace('BUY-qualified calls keep the official +0.30% net accuracy score. Ranks 4–15 are forward shadow snapshots. v1.6.1 additionally learns bullish-regime and HOD-breakout subsets instead of treating every shadow sample alike. Late vertical spikes are still penalized. Learning cannot override protection, liquidity, spread, clear-path, re-entry or 30-minute rules.','BUY-qualified calls inside the 09:15–14:40 entry window keep the official +0.30% net accuracy score. Ranks 4–15 and post-cutoff candidates remain shadow learning. v1.6.4 adds pattern-memory veto, 2-stage 1-minute persistence and momentum-decay rejection. Late spikes, protection, liquidity, spread, clear-path and 30-minute rules remain hard.')
s=s.replace('v1.6.3 • depth-aware spread + ₹10K charge-aware target • standalone package com.suhas.nseunifiedscanner','v1.6.4 • pattern memory + 2-stage confirmation • ₹10K test mode • standalone package com.suhas.nseunifiedscanner')

old_render='''        LearningStore.Stats s=learning.stats();if(s.n==0){successRate.setText("—");successRate.setTextColor(TEXT);successSub.setText("No resolved scanner recommendations yet • goal ≥80%, never guaranteed");}else{successRate.setText(String.format(Locale.US,"%.1f%%",s.rate));successRate.setTextColor(s.rate>=80?GREEN:s.rate>=70?AMBER:RED);String confidence=s.n<20?"LOW CONFIDENCE":s.n<50?"BUILDING CONFIDENCE":"ROLLING EVIDENCE";successSub.setText(s.wins+"/"+s.n+" target hits • "+confidence+" • executed "+s.executedN+" • goal ≥80%, not guaranteed");}\n        LearningInsights.PipelineStats pipe=insights.pipelineStats();'''
new_render='''        LearningStore.Stats s=learning.stats();LearningInsights.TodaySummary today=insights.todaySummary();double todayRate=today.resolved==0?Double.NaN:(100.0*today.hits/today.resolved);if(s.n==0){successRate.setText("—");successRate.setTextColor(TEXT);successSub.setText("TODAY "+(today.resolved==0?"no resolved tradable calls":(today.hits+"/"+today.resolved+" = "+String.format(Locale.US,"%.1f%%",todayRate)))+" • rolling sample not established");}else{successRate.setText(String.format(Locale.US,"%.1f%%",s.rate));successRate.setTextColor(s.rate>=80?GREEN:s.rate>=70?AMBER:RED);String confidence=s.n<20?"LOW CONFIDENCE":s.n<50?"BUILDING CONFIDENCE":"ROLLING EVIDENCE";String td=today.resolved==0?"TODAY: none resolved":("TODAY "+today.hits+"/"+today.resolved+" = "+String.format(Locale.US,"%.1f%%",todayRate));successSub.setText(td+" • rolling "+s.wins+"/"+s.n+" • "+confidence+" • executed "+s.executedN+" • goal ≥80%, not guaranteed");}\n        LearningInsights.PipelineStats pipe=insights.pipelineStats();'''
if old_render not in s: raise SystemExit('v1.6.4 MainActivity render anchor missing')
s=s.replace(old_render,new_render,1)

old='''double ep=r.features.optDouble("earlyPressure",0),va=r.features.optDouble("volumeAccel",0),p5=r.features.optDouble("price5mPct",0);boolean late=r.features.optBoolean("lateSpike",false);c.addView(txt("Setup "+setup+" • EARLY "+String.format(Locale.US,"%.0f/100",ep)+" • vol accel "+String.format(Locale.US,"%.2fx",va)+" • 5m "+String.format(Locale.US,"%+.2f%%",p5)+(late?" • LATE SPIKE ✗":""),11,late?RED:ACCENT,false));c.addView(txt("prior HOD "+(hod>0?("₹"+money(hod)):"—")+" • target-clearance "+String.format(Locale.US,"%+.2f%%",hodRoom)+" • recovery "+String.format(Locale.US,"%.2f%%",recov),11,r.features.optBoolean("clearPath",true)?MUTED:RED,false));c.addView(space(8));'''
new='''double ep=r.features.optDouble("earlyPressure",0),va=r.features.optDouble("volumeAccel",0),p5=r.features.optDouble("price5mPct",0);boolean late=r.features.optBoolean("lateSpike",false),confirm=r.features.optBoolean("confirmation",false),decay=r.features.optBoolean("momentumDecay",false);int pn=r.features.optInt("patternN",0),ph=r.features.optInt("patternHits",0);double pr=r.features.optDouble("patternRate",0);c.addView(txt("Setup "+setup+" • EARLY "+String.format(Locale.US,"%.0f/100",ep)+" • vol accel "+String.format(Locale.US,"%.2fx",va)+" • 5m "+String.format(Locale.US,"%+.2f%%",p5)+(confirm?" • CONFIRM ✓":" • CONFIRM …")+(decay?" • DECAY ✗":"")+(late?" • LATE SPIKE ✗":""),11,(late||decay)?RED:ACCENT,false));c.addView(txt("pattern memory "+ph+"/"+pn+" • posterior "+String.format(Locale.US,"%.0f%%",pr*100)+" • prior HOD "+(hod>0?("₹"+money(hod)):"—")+" • target-clearance "+String.format(Locale.US,"%+.2f%%",hodRoom)+" • recovery "+String.format(Locale.US,"%.2f%%",recov),11,r.features.optBoolean("patternVeto",false)?RED:(r.features.optBoolean("clearPath",true)?MUTED:RED),false));c.addView(space(8));'''
if old not in s: raise SystemExit('v1.6.4 MainActivity candidate anchor missing')
s=s.replace(old,new,1)

s=s.replace('b.append(r.features.optBoolean("spreadKnown",false)&&r.spreadPct<=0.20?"✓SPREAD ":"✗SPREAD ");\n        b.append(r.features.optBoolean("clearPath",true)?"✓PATH ":"✗PATH ");',
'''b.append(r.features.optBoolean("spreadKnown",false)&&r.spreadPct<=0.20?"✓SPREAD ":"✗SPREAD ");\n        b.append(r.features.optBoolean("confirmation",false)?"✓CONF ":"✗CONF ");\n        b.append(!r.features.optBoolean("patternVeto",false)?"✓PATTERN ":"✗PATTERN ");\n        b.append(r.features.optBoolean("clearPath",true)?"✓PATH ":"✗PATH ");''')

s=s.replace('Market breadth %.1f%%\\n\\n%s",r.symbol,r.entry,r.target,r.stop,r.rsi,r.relVol,r.oneHour,r.vwap,r.r1,r.r2,r.roomR2,(r.spreadPct>=0?(String.format(Locale.US,"%.3f%% [%s]",r.spreadPct,r.features.optString("spreadSource","TOP"))):"UNKNOWN"),r.breadth,r.reason)',
'''Market breadth %.1f%%\\n1m confirmation %s\\nMomentum decay %s\\nPattern memory %d/%d • posterior %.0f%%\\n\\n%s",r.symbol,r.entry,r.target,r.stop,r.rsi,r.relVol,r.oneHour,r.vwap,r.r1,r.r2,r.roomR2,(r.spreadPct>=0?(String.format(Locale.US,"%.3f%% [%s]",r.spreadPct,r.features.optString("spreadSource","TOP"))):"UNKNOWN"),r.breadth,(r.features.optBoolean("confirmation",false)?"YES":"NO"),(r.features.optBoolean("momentumDecay",false)?"YES":"NO"),r.features.optInt("patternHits",0),r.features.optInt("patternN",0),r.features.optDouble("patternRate",0)*100,r.reason)''')
mp.write_text(s)

s=gp.read_text();s=re.sub(r'versionCode\s+\d+', 'versionCode 164', s, count=1);s=re.sub(r"versionName\s+'[^']+'", "versionName '1.6.4'", s, count=1);gp.write_text(s)

print('v1.6.4 pattern-memory + 2-stage confirmation patch applied')
