name: Test Artifact Builder

on:
  push:
    branches: [test-actions-apk-builder]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create artifact
        run: echo hello > hello.txt
      - uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: hello.txt
